### ISSUE TITLE
Remove empty VAR's

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#1]
Remove empty VAR's in function blocks, methods etc.

```
// in
METHOD Name
VAR_INPUT
    Variable : DINT;
END_VAR
VAR
END_VAR

// out
METHOD Name
VAR_INPUT
    Variable : DINT;
END_VAR
```

**Comment by Barteling** [comment]
This is an use full addition! I put it on my list. But my first focus is on code layout, Stability and features of the formatter. 
In a second stage of STweep I will concentrate more on code clean up like this. 
I will close this for now
