### ISSUE TITLE
Improve formatting of fluent interfaces

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#10]
Currently when you format a fluent interface, it chains all of them together and breaks after the dot.

```
\\ in
ErrorString := _stringBuilder
                .Reset()
                .Append('Error number: ')
                .Append(INT_TO_STRING(ErrorNumber))
                .Append('. Message: ')
                .Append(ErrorMessage)
                .Append('.')
                .ToString();

\\out
ErrorString := _stringBuilder.Reset().Append('Error number: ').Append(INT_TO_STRING(ErrorNumber)).
	Append('. Message: ').Append(ErrorMessage).Append('.').ToString();
```

I think it is better to 1) break before the dot and 2) keep each statement on a separate line, if they exceed the maximum length. I guess aligning each method call would be an option. Personally I'm not a fan of aligning statements, since they can introduce unnecessary diffs when you change the name of a variable/method and rerun STweep with alignment options enabled. Anyway something like this would be a better result after formatting:

```
ErrorString := _stringBuilder
	.Reset()
	.Append('Error number: ')
	.Append(INT_TO_STRING(ErrorNumber))
	.Append('. Message: ')
	.Append(ErrorMessage)
	.Append('.')
	.ToString();
```

This is another case caused by setting "Keep existing line breaks" to false. 

- STweep v1.0.6-beta
- [settings.txt](https://github.com/Barteling/STweep/files/5807294/settings.txt)

**Comment by Barteling** [comment]
I will look at it. It will probably come with settings > Prefer wrap before or after DOT in chained methods.
Chained method wrapping: Break always, break if line length over flow,   break if line length overflow or multiline
Like you have chained binary expressions.

**Comment by Barteling** [comment]
I  improved formatting of fluent interfaces in STweep for TwinCAT beta 3.3.0 and Stweep for Codesys 3.3.0

https://www.stweep.com/codesys-beta-releases/
https://www.stweep.com/releases/
