### ISSUE TITLE
VAR_INST in method causes invalid operation exception

### ISSUE THREAD

**Issue by RogerChristopher** [Barteling/STweep#13]
See screenshot - if I change the VAR_INST to VAR, formatter works correctly

Using STweep 1.0.3.0 

![Capture](https://user-images.githubusercontent.com/32986382/104724562-bdd39300-5728-11eb-97a3-19dfec977212.PNG)

**Comment by RogerChristopher** [comment]
Just updated to 1.0.6 and it seems to be fixed.

**Comment by Barteling** [comment]
This was fixed in 1.0.4 and higher. Thanks for confirming.
