### ISSUE TITLE
IF statements on single line

### ISSUE THREAD

**Issue by Barteling** [Barteling/STweep#15]
I've had some requests to place IF statements under certain conditions on a single line:
<PRE>
IF Condition THEN Action(); END_IF
</PRE>

mostly because programmers something prefer to stack them like:
<PRE>
IF Condition THEN Action(); END_IF
IF Condition2 THEN Action2(); END_IF
IF Condition3 THEN Action3(); END_IF
</PRE>

instead of:
<PRE>
IF Condition THEN
    Action();
END_IF

IF Condition2 THEN
    Action2();
END_IF

IF Condition3 THEN
    Action3();
END_IF
</PRE>

How would you like to see this implemented?,
 - If the if statement is on single line, leave it like that during formatting (except line lengths overflows).
 - If the if statement is simple place it on one line. Simple meaning, one condition, one action, no ELSIF or ELSE
 - if the complete if statement fits on single line, place it on a single line.
 - a combination of above?
 - Something else?

**Comment by HAHermsen** [comment]
Hi,

Just my two cents:

IMHO, stacking does not improve readability. The PLCOpen guidelines clearly say to write this over into amultiline with a mandatory ELSE clause, but this last point is a bit to strict if you ask me.
I dare to even say thatyour example could be rewritten to a case:  Condition1, 2 and 3 can be refactored into a single enumerator.

I think STweep could do with several settings to:
A) Add an option to rewrite the single line IF THEN into multiline, basically following "If the if statement is on single line, leave it like that during formatting (except line lengths overflows" except the user can now also enforce multine.
B) Add an extra settings option to insert a ELSE clause which is only selectable if A is TRUE.

With kind regards






Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Roald87** [comment]
My two cents. For me putting the complete IF statement on a single line is also not necessary. I do not get this obsessive behavior over putting everything on a single line anyway. Usually readability is better when statements always have the same format.

**Comment by RogerChristopher** [comment]
I agree with Roald.

**Comment by Barteling** [comment]
Thanks, based on your response I believe it does not have to be high on the priority list
