### ISSUE TITLE
Part of recently added declaration and implementation disappeared

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#19]
## Disclaimer
I just had the strangest thing and I'm not sure if it has to do with STweep, but I wanted to report it anyway. Since I have never seen it before and I just started using a new STweep version, so maybe that had something to do with it.

## Issue
I added a variable and a method to a function block, did some tests and committed my changes. Note: I of course used STweep to format it. 

The change was something like:

```diff
FUNCTION_BLOCK FB_Foo
VAR
    fb1 : FB_Bar;
    fb2 : FB_Bar;
+   fb3 : FB_Bar;
END_VAR

======

Method1();
Method2();
+Method3();
```

A little while later I opened `FB_Foo` again, but then the lines with `fb3` and `Method3();` were gone. The changes were in my git history and I did not see any changes in git that `fb3` and `Method3();`. Then I added them again and build my project. However, then I got a build error:

`VAR, VAR_INPUT, VAR_OUTPUT or VAR_INOUT expected instead of b3:FB_Foo;`

It turned out that somehow, the old `fb3` was still there, and when I re-added the new `fb3` it put is somewhere at a random position in the middle of the old declaration. I think it was something like:

```
FUNCTION_BLOCK FB_Foo
VAR
    fb1 : FB_Bar;
    fb2 : FB_Bar;
   fb3 : FB_Bar;
ENDfb3 : FB_Bar;_VAR
```

I'll let you know if it occurs again. I don't know how to reproduce it yet.

## Info
- STweep 2.0.1
- Visual Studio Community 15.9.29
- [settings.txt](https://github.com/Barteling/STweep/files/5895003/settings.txt)

**Comment by Barteling** [comment]
Strange, just let me know if it occurs again.

**Comment by Barteling** [comment]
I'll close this for now, but of course let me now if it happens again.
