### ISSUE TITLE
New lines are added on each STweep call at the end of the file

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#23]
In the example below a new line is added each time I press Ctrl + 4. 

![new_lines](https://user-images.githubusercontent.com/20192767/108071486-11a60480-7066-11eb-99ab-9e91a9a46ba5.gif)

- STweep v3.0.0-beta
- [settings.txt](https://github.com/Barteling/STweep/files/5988997/settings.txt)

**Comment by Barteling** [comment]
Fixed in 3.0.1-Beta
