### ISSUE TITLE
TwinCAT - Invocation

### ISSUE THREAD

**Issue by bobbyzap** [Barteling/STweep#27]
Not seeing the desired output for two settings.
- Line break after '(' and before ')' in invocation. 
- Alignment - Invocation call parameters. Not lining up opening parenthesis. 

**STweep version info**
TwinCAT 3.10 Installed in TcXaeShell

**Comment by bobbyzap** [comment]
`// Open / close issue
istep                          := 0;
steps[istep].Description       := 'INITIAL';
steps[istep].Perm.P[1].inpPerm := steps[0].outStepActive;
steps[istep].Perm.P[2].inpPerm := TRUE;
steps[istep](cfgStep             := 0,
             cfgStepTimerSeconds := E_wFovStep.initial,
             cfgNextStep         := E_wFovStep.check_health,
             TSM                 := THIS^);



// alignment issue
istep                              := E_wFovStep.check_health;
steps[istep].Description           := 'CHECK HEALTH';
steps[istep].Perm.P[1].Description := '';
steps[istep].Perm.P[1].inpPerm     := steps[istep].outStepActive;
steps[istep](
    cfgStep             := istep * 10,
    cfgStepTimerSeconds := 0,
    cfgNextStep         := E_wFovStep.start_robots * 10,
    TSM                 := THIS^
    );
`

**Comment by Barteling** [comment]
@bobbyzap  could you share a code example where this happens and an export of your settings?

**Comment by bobbyzap** [comment]
arguments are not moving to a new line. Unable to upload files due to security policy at work. 

```
(********** INITIAL STEP ***********)
istep                          := 0;
steps[istep].Description       := 'INITIAL';
steps[istep].Perm.P[1].inpPerm := steps[0].outStepActive;
steps[istep].Perm.P[2].inpPerm := TRUE;
steps[istep](cfgStep             := 0,
             cfgStepTimerSeconds := E_wFovStep.initial,
             cfgNextStep         := E_wFovStep.check_health,
             TSM                 := THIS^);
```

**Comment by Barteling** [comment]
Fixed over email
