### ISSUE TITLE
Preview should show combined effect of selected options

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#28]
There are a lot of options and it is sometimes confusing what the effect is of a certain option combination. See for example #9. If would be nice if the options preview 

![image](https://user-images.githubusercontent.com/20192767/110910525-c0f69400-8311-11eb-909b-b4f55c275a2d.png)

showed the combined effect of the selected options instead of the effect of one of them.

**Comment by Barteling** [comment]
This is something I considered
There is however a drawback on this, a lot of settings have no effect when certain other settings are set
So you change a setting, watch the preview, and nothing happens..

This is why I always show the preview with a set of settings which always shows the effect of a setting.

An alternative would be to show the preview with your current set of settings, and override those needed for a correct preview. But you still might be fooled with the outcome.

**Comment by HAHermsen** [comment]
A nice idea, but how could it be presented to the user in a clear fashion?
I can imagine a new preview pane with a "chunck of code" which shows the compounded preview settings.

**Comment by Roald87** [comment]
> So you change a setting, watch the preview, and nothing happens..

Maybe those should be greyed out? 

I think something like how its done in the Visual studio options is pretty clear.

![formatting_options](https://user-images.githubusercontent.com/20192767/111025312-97a63880-83e3-11eb-9331-95cdd104e1d2.gif)

**Comment by HAHermsen** [comment]
Any feedback on this feature or is it on the backburner?

**Comment by Barteling** [comment]
Hmm, I think at one point I will go for this. 

However, for now I prefer to spent my time on bug fixes, formatting features, STweep CLI.

**Comment by Barteling** [comment]
Changed in 4.1.0- Beta
https://www.stweep.com/beta-releases/

I leave this issue open to hear your experiences with this new behaviour
