### ISSUE TITLE
"Check for updates" window shows wrong version as latest one

### ISSUE THREAD

**Issue by sagatowski** [Barteling/STweep#29]
**Describe the bug**
The "Check for updates" window seems to show wrong version as the latest one. If have version 3.1.4 installed but it shows that the latest version is 3.1.3. See attached screenshot.

![latestversion](https://user-images.githubusercontent.com/33381702/111140499-af67f300-8582-11eb-9646-0600668b829b.png)

**STweep version info**
STweep version 3.1.4.

**IDE version info**
TwinCAT XAE 3.1.4024.12 + TcXaeShell

**Comment by Barteling** [comment]
Thanks,
Fixed it on the server side.

**Comment by sagatowski** [comment]
Seems to work fine, good job.
![image](https://user-images.githubusercontent.com/33381702/111270920-c402c480-8630-11eb-9531-cc00c9732649.png)
