### ISSUE TITLE
Preview of Line break after '[' in array initializer doesn't update

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#35]
All the array boolean options update the preview, except the line break after `[`.

![array_initializer](https://user-images.githubusercontent.com/20192767/111604450-a28f0d80-87d5-11eb-8fa2-f4e747ac5234.gif)

Problem only seems in the preview. When formatting the real code, it does place a line break after `[`.

- STweep: TwinCAT 3.1.5-Beta
- IDE: Microsoft Visual Studio Community 2017 Version 15.9.33

**Comment by Barteling** [comment]
Thanks for noting,
I see the problem.

The preview code is 
<pre>
Variable2 : ARRAY[0..2] OF BOOL [TRUE, FALSE];
</pre>
This is however not an array initializer but a function block initializer and starting with 3.1.5-Beta treated as such.
The difference is ':=', is should be:
<pre>
Variable2 : ARRAY[0..2] OF BOOL := [TRUE, FALSE];
</pre>

I'll update the preview code in the next release.

**Comment by Barteling** [comment]
Fixed in 3.2.0 Beta
