### ISSUE TITLE
Visual Studio warning about STweep unresponsivemess

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#41]
Since I installed STweep 3.4.0 I get this warning when I start Visual Studio 2017 Community 15.9.33:

![image](https://user-images.githubusercontent.com/20192767/114710327-dd7d5600-9d2d-11eb-816e-a1ddbbd6910a.png)

I didn't see this warning with =< v3.3.

Did something change in the background which makes the extension a lot slower since v3.4?

**Comment by Barteling** [comment]
Actually I have seen this as well myself. But i'm not sure why, the package complies with all Visual studios requirements in terms of background loading and in this last version nothing changed in that. 
The only thing what takes times is the license check with the server. This depends a bit on the internet connection. 
When did this message occur, before or after loading a solution?

**Comment by Roald87** [comment]
After loading the solution.

**Comment by Barteling** [comment]
Ok, and have you also noticed the delay or was it more a false positive message of visual studio?

**Comment by Roald87** [comment]
Not really, just the message. Although opening this particular solution is always very slow. So it is difficult to say if it was slower with the new Stweep version. 

Anyway, you can close it if you'd like. I just wanted to let you know.

**Comment by Barteling** [comment]
Ok, yes thanks for noting!
I'll close it for now but let me know if you encounter this more often.
