### ISSUE TITLE
STweep formats arrays without bounds

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#42]
**Describe the bug**
The following code has no bounds for the array. Usually when you try to format code with an error, STweep doesn't do anything. In this case it will format the code

```
// in
FUNCTION_BLOCK POU
VAR_INPUT
	anArray : ARRAY OF ST_AdsAddress[
		(Channel:=1, NetId:='123.124.123.52', Port:=87),
		(Channel:=1, NetId:='123.124.123.52', Port:=87)
	];
END_VAR

//out
FUNCTION_BLOCK POU
VAR_INPUT
	anArray : ARRAY OF
	ST_AdsAddress[
		(
	Channel:=1,
	NetId:='123.124.123.52',
	Port:=87),
		(
	Channel:=1,
	NetId:='123.124.123.52',
	Port:=87)
	];
END_VAR
```

Once you add array bounds it will format correctly.

```
//output
FUNCTION_BLOCK POU
VAR_INPUT
	anArray : ARRAY[1..2] OF ST_AdsAddress[
		(Channel:=1, NetId:='123.124.123.52', Port:=87),
		(Channel:=1, NetId:='123.124.123.52', Port:=87)
	];
END_VAR
```

**Expected behavior**
I do not expect STweep to format anything in such a case.

STweep  v3.4.0. 
Microsoft Visual Studio Community 2017 Version 15.9.33
[settings.txt](https://github.com/Barteling/STweep/files/6397123/settings.txt)

**Comment by Barteling** [comment]
I'll check it.

_Usually when you try to format code with an error, STweep doesn't do anything._
When there are parsing errors STweep skips the part with the parsing error, But for example when a statement has a parsing error STweep may attempt to format a next statement if it does not have a parsing error.
