### ISSUE TITLE
Bug or feature / comment in function block call are treated as they are a part of the affectation

### ISSUE THREAD

**Issue by GISED-Link** [Barteling/STweep#46]
**Describe the bug**
When I call a FB, like fb_theBesFbEverMade(), if the line is too long STWeep tries to slice it, wich is good. But STWeep seems to also take in account the comment part. I think it is the only place where the comment is taken in account (compared to variable declaration or affectation outside a FB call).
Maybe I have a parameter wrong?

**Expected behavior**
 - The initial code before formatting
```
fb_axis145_10W(wAxisState := simu_axis145_10W.wOUT_AxisState); // The simu fb gives us the hardware signal when we are not in simulation
```
 - The current result after formatting
 
```
fb_axis145_10W(wAxisState := simu_axis145_10W
                   .wOUT_AxisState); // The simu fb gives us the hardware signal when we are not in simulation
```
 - The expected result.
```
fb_axis145_10W(wAxisState := simu_axis145_10W.wOUT_AxisState); // The simu fb gives us the hardware signal when we are not in simulation
```

**STweep version info**
STweep for TwinCAT 3.5.0-Beta

[stweep_RS_2021_06_03.zip](https://github.com/Barteling/STweep/files/6590747/stweep_RS_2021_06_03.zip)

**Comment by Barteling** [comment]
Thanks for your report,
I can reproduce your results.

But I think it is as expected. STweep always takes end of line comments into account for maximum line length. And I believe that is as it should be.

Even here on github, I find the formatted example easier readable:
![image](https://user-images.githubusercontent.com/33071638/120637465-3dab9100-c46f-11eb-8f8c-6e0c0951b3b6.png)

I'll leave this open for perhaps a short discussion but I don't think it is a bug

**Comment by GISED-Link** [comment]
Thank's for the feedback. I was myself not sure (it is why you see bug / feature in the title). I think the best thing to do with such a case is to put this comment above.

Oh and I see that you haven't choosen the dark (theme) side of github.

**Comment by Barteling** [comment]
`I think the best thing to do with such a case is to put this comment above.`
i agree.

`Oh and I see that you haven't choosen the dark (theme) side of github.`
Contrary to most developers i'm not to fond of dark themes^^ 
I'm pretty happy with the windows Night light function which I use all day long.
