### ISSUE TITLE
Error on opening TcXaeShell 4024.20

### ISSUE THREAD

**Issue by elconfa** [Barteling/STweep#48]
After copying the beta files (3.6.4.BETA) I have this error.

  <entry>
    <record>592</record>
    <time>2021/09/20 06:16:29.311</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [STweepPackage]</description>
    <guid>{88A658A1-DCBF-4EF3-A8CF-636FA7F6E813}</guid>
  </entry>
  <entry>
    <record>593</record>
    <time>2021/09/20 06:16:29.322</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [STweepPackage]Source: &apos;mscorlib&apos; Description: Non &#x00E8; stato possibile caricare il file o l&apos;assembly &apos;file:///c:\program files (x86)\beckhoff\tcxaeshell\common7\ide\extensions\stweep\STweep.TwinCAT.dll&apos; o una delle relative dipendenze. Operazione non supportata. (Eccezione da HRESULT: 0x80131515)&#x000D;&#x000A;System.IO.FileLoadException: Non &#x00E8; stato possibile caricare il file o l&apos;assembly &apos;file:///c:\program files (x86)\beckhoff\tcxaeshell\common7\ide\extensions\stweep\STweep.TwinCAT.dll&apos; o una delle relative dipendenze. Operazione non supportata. (Eccezione da HRESULT: 0x80131515)&#x000D;&#x000A;File name: &apos;file:///c:\program files (x86)\beckhoff\tcxaeshell\common7\ide\extensions\stweep\STweep.TwinCAT.dll&apos; ---&gt; System.NotSupportedException: &#x00C8; stato effettuato un tentativo di caricamento di un assembly da un percorso di rete, il che avrebbe causato la creazione mediante sandbox dell&apos;assembly nelle versioni precedenti di .NET Framework. In questa versione di .NET Framework i criteri di sicurezza dall&apos;accesso di codice non sono abilitati per impostazione predefinita, pertanto questo tipo di caricamento pu&#x00F2; risultare pericoloso. Se il caricamento non &#x00E8; effettuato per creare l&apos;assembly mediante sandbox, abilitare l&apos;opzione loadFromRemoteSources. Per ulteriori informazioni, vedere http://go.microsoft.com/fwlink/?LinkId=155569.&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.NotSupportedException: &#x00C8; stato effettuato un tentativo di caricamento di un assembly da un percorso di rete, il che avrebbe causato la creazione mediante sandbox dell&apos;assembly nelle versioni precedenti di .NET Framework. In questa versione di .NET Framework i criteri di sicurezza dall&apos;accesso di codice non sono abilitati per impostazione predefinita, pertanto questo tipo di caricamento pu&#x00F2; risultare pericoloso. Se il caricamento non &#x00E8; effettuato per creare l&apos;assembly mediante sandbox, abilitare l&apos;opzione loadFromRemoteSources. Per ulteriori informazioni, vedere http://go.microsoft.com/fwlink/?LinkId=155569.</description>
    <guid>{88A658A1-DCBF-4EF3-A8CF-636FA7F6E813}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

![image](https://user-images.githubusercontent.com/58783001/133963029-8d9b774e-4191-490b-933b-c32ff286e8cc.png)

**Comment by Barteling** [comment]
My Italian is not what is used to be, but it looks like it cannot find the STweep.Formatter.Dll
Did you make sure to unblock the files before copying as described here?
https://www.stweep.com/documentation/installation-guide-twincat-xae-shell/

**Comment by elconfa** [comment]
You are right. Thanks for the fast answer
