### ISSUE TITLE
Add trailing comma after last argument in method/FB call for smaller diffs

### ISSUE THREAD

**Issue by Roald87** [Barteling/STweep#5]
If a comma is added after the last argument in a function call for functions with a lot of arguments, then the diff will be smaller if you add a new argument later on.

Example without last trailing comma

```diff
FB_Something(
    Arg1:=1,
-    Arg2:=2
+    Arg2:=2,
+    Arg3:=3
);
```
Example with last trailing comma

```diff
FB_Something(
    Arg1:=1,
    Arg2:=2,
+    Arg3:=3,
);
```

**Comment by Barteling** [comment]
as with #1  a good addition, it's on the list but in a later stage
