### ISSUE TITLE
STweep doesn't format some DUT's files

### ISSUE THREAD

**Issue by GISED-Link** [Barteling/STweep#50]
**Describe the bug**
sometimes STweep simply refuses to work on some DUT files. I have join the complete file because when I copy paste the code on another DUT where STweep runs, the code is correctly formated. The problem seems on the things around the code itself.

This is a file where STweep works:
[ST140_Alarm_e (working).zip](https://github.com/Barteling/STweep/files/7888395/ST140_Alarm_e.working.zip)

This is a file where STweep doesn't work:
[ST150_Cylinders_e (not working).zip](https://github.com/Barteling/STweep/files/7888397/ST150_Cylinders_e.not.working.zip)

How to reproduce:

1. Import both files in your project
2. Try to format the code in ST150_Cylinders_e. If it works, try to replace all its content with the given file again using a text editor to be sure that the file is really the same. If not, bingo we can reproduce
3. Delete content of ST140_Alarm_e
4. Copy the content of ST150_Cylinders_e and past it in ST140_Alarm_e. If you can format the code in ST140_Alarm_e and not in ST150_Cylinders_e, then it will be easier to understand why it is not working

In my case:

-  closing the solution and reopen it doesn't fix the issue
- closing Twincat XAE completely and reopen it doens't fix the issue
- rebuild the solution doesn't fix the issue

**Expected behavior**
Should format the code

**STweep version info**
STweep for TwinCAT 3.6.5

**IDE version info**
TcXaeShell 15.28010.2050
Twincat build 4024.12

**My STweep settings**
[STweep_settings GISED_LINK.zip](https://github.com/Barteling/STweep/files/7888469/STweep_settings.GISED_LINK.zip)

**Comment by Barteling** [comment]
Thanks for the thorough report. I could reproduce it.

I think it's related to the setting "Add text file support". 
If i disable this it seems to work as expected. Can you confirm this?
![Untitled](https://user-images.githubusercontent.com/33071638/150088277-3a70f5d0-3b47-4f9b-b5e4-696b15cba91a.png)

**Comment by GISED-Link** [comment]
Yes, I can confirm. Extension of the problematic files are *.TcLEO and not *.TcDUT due to this textlist support

Hopefully I don't need this "text file support" anymore since I am not doing visualization from Twincat anymore.

**Comment by Barteling** [comment]
Ok, i''ll see to add support for these files in a next release version nevertheless.
