### ISSUE TITLE
No solution found when MaxStructureInitializerParametersOnSingleLine value is too small

### ISSUE THREAD

**Issue by tan-wei-xin-alez** [Barteling/STweep#53]
**Describe the bug**
Formatting the following code using STweep with `"MaxStructureInitializerParametersOnSingleLine": 5`
```
TYPE
  testStruct :
  STRUCT
    x : LREAL;
    y : LREAL;
    z : LREAL;
    a : LREAL;
    b : LREAL;
    c : LREAL;
  END_STRUCT
END_TYPE
```
```
FUNCTION_BLOCK TestPOU
VAR
  arrTest : ARRAY[0..2] OF testStruct := [(x:=0, y:=0, z:=0, a:=0, b:=0, c:=0), (x:=0, y:=0, z:=0, a:=0, b:=0, c:=0)];
END_VAR
```
causes STweep to throw the following exception in CODESYS
```
System.AggregateException:One or more errors occurred.---> System.InvalidOperationException:No solution found
at a.m.A(ReadOnlyCollection`1,STFormattingSettings , CancellationToken )
at A.r.A(String ,CancellationToken )
at A.r.a.A()
at System.Threading.Tasks.Task`1,InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.Task.Awaiter.ThrowforNonS uccess(Task task)
at System.Runtime.CompilerServices.Task.Awaiter.HandleNonSucc essAndDebuggerNotification(Task task)
at A.r.B.MoveNext()
--- End of inner exception stacktrace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1,GetResultCore(Boolean waitCompletionNotification)
at System.Threading.Tasks.Task`1,get_Result()
at A.L.A(b ) 
at A.P.A()
---> (Inner Exception #0) System.InvalidOperationException:
No solution found
at a.m.A(ReadOnlyCollection`1,STFormattingSettings, CancellationToken )
at A.r.A(String ,CancellationToken )
at A.r.a.A()
at System.Threading.Tasks.Task`1,InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.Task.Awaiter.ThrowforNonSuccess(Task task)
at System.Runtime.CompilerServices.Task.Awaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at A.r.B.MoveNext() <---
```
<br>

Adding a line break between `:=` and `[` causes the exception to go away and results in the following
```
FUNCTION_BLOCK TestPOU
VAR
  arrTest : ARRAY[0..2] OF testStruct :=
  [
    (x:=0,
     y:=0,
     z:=0,
     a:=0,
     b:=0,
     c:=0),
    (x:=0,
     y:=0,
     z:=0,
     a:=0,
     b:=0,
     c:=0)
  ];
END_VAR
```
<br>

Increasing `MaxStructureInitializerParametersOnSingleLine` to `6` also causes the exception to go away

**Expected behavior**
Either a warning to change the value of `MaxStructureInitializerParametersOnSingleLine` for formatting to succeed or the following result
```
FUNCTION_BLOCK TestPOU
VAR
  arrTest : ARRAY[0..2] OF testStruct :=
  [
    (x:=0,
     y:=0,
     z:=0,
     a:=0,
     b:=0,
     c:=0),
    (x:=0,
     y:=0,
     z:=0,
     a:=0,
     b:=0,
     c:=0)
  ];
END_VAR
```

**STweep version info**
STweep formatter for Codesys 3.5.2

**IDE version info**
CODESYS V3.5 SP16 Patch 4 + (32-bit)

**STweep settings**
[codesys_formatting.txt](https://github.com/Barteling/STweep/files/7959389/codesys_formatting.txt)

**Comment by Barteling** [comment]
Could you upload your settings file ? if you change the extension from .stweep to .txt you can upload it. 
Now i miss the checksum.

**Comment by tan-wei-xin-alez** [comment]
> Could you upload your settings file ? if you change the extension from .stweep to .txt you can upload it. Now i miss the checksum.

Ahhhh so drag and drop is how you do it, couldn't find a button for attachments so I was just copy and pasting the contents
I've updated the issue with the txt file

**Comment by Aliazzzz** [comment]
Hi, lemme confirm this on my box too ;-) Wait for it please.

**Comment by Barteling** [comment]
I cannot repeat it with your settings and example, i changed structure initializers back from 10 to 5.
But, i'm running on the latest version in TwinCAT, please wait for the 4.0.0 release on Monday and try it again. 
(Before i start spending my weekend on a problem which is already solved^^)

**Comment by tan-wei-xin-alez** [comment]
> I cannot repeat it with your settings and example, i changed structure initializers back from 10 to 5. But, i'm running on the latest version in TwinCAT, please wait for the 4.0.0 release on Monday and try it again. (Before i start spending my weekend on a problem which is already solved^^)

Yep, you were right. Does not happen in 4.0.0 release so considered fixed,
