### ISSUE TITLE
Option to indent all declaration types to the furthest indention

### ISSUE THREAD

**Issue by crthomas1234** [Barteling/STweep#54]
When formatting your variable declarations, I would like the option to align the : <var type> to the longest variable name indention in order to keep all declarations in a single column.

I would also like to have this option for declaration comments.

**Comment by Barteling** [comment]
Could you make me an example with some code before and after formatting?

**Comment by crthomas1234** [comment]
Hi Gerhard.

Thank you for your email and considering my request.  I purchased the
program yesterday and am really happy with it.  I have wanted something
like this for so long as I spend so much time going back and cleaning up my
code.  I had often thought of how I could use python scripting for
something like this.  And then STWeep came along and fixed this for me.  A
lot of my coworkers think I am crazy with the amount of time I spend
indenting and aligning everything.  But my brain refuses to let me have
poorly formatted code.  So thank you for this product.

For example, I have created 2 images with some descriptions of what I think
the options could be.  Currently, it seems that the alignment is done in
sections.  So when there is a singular comment on in a line of code,
this is treated like a section and only the variables in that section are
aligned.  There are a few edge cases I mention in the images where the
variables have an initial value declared or the data type used is very
long.  In these cases, indenting to the longest name would create
undesirable amounts of indention.  So I was thinking that we could have a
rule that variables with initial values are ignored.  Or maybe better is
that there is a maximum number of characters, including initial values that
causes the indention logic to be skipped and that comment is only
indented out once.

Please reach out to me if you have any questions or you need clarification.

Best regards,

Chris Thomas

**Comment by Barteling** [comment]
Hi Chris,

I also don't like poor formatted code so that was the reason i developed STweep haha.
I don't see the picture you talk about, got you perhaps drop them here directly on github?

**Comment by crthomas1234** [comment]
Hi Gerhard.  Here are the images from before / after my request.

![STWeep_desired_formatting](https://user-images.githubusercontent.com/98989074/152820165-7cafae70-ac39-4b97-b4af-095bb64af641.png)
![STWeep_current_formatting](https://user-images.githubusercontent.com/98989074/152820189-d13aec96-fe62-4d4a-bf29-b4b0efb43ede.png)
.

**Comment by Barteling** [comment]
This is the main reason I personally don't like the options of alignment in columns ^^ But l made Stweep configurable with a reason, opinions and tastes differ.

Some of my thoughts:
One of the reasons STweep aligns columns only if the elements are on consecutive lines is to give you the option to handle edge with very long variable a type names, Like you showed on the first picture.

Supporting the edge case point: in terms of clean code you should not have groups in your GVL separated by comments in the first place. If you find yourself doing this you have to ask yourself what is going wrong. In this case: If you want groups, you should use a DUT to bundle variables in a group rather then comments.

Another reason, is the line breaking algorithm, one of Stweep best functionalities in my opinion.
If Stweep decides that line is too long and should be broken, this will stop the alignment in columns algorithm. And start a new alignment group. If i would not that I cannot improve on line length limits.
For example:
```
Line length limit                    |
LongVariableName1 : BOOL;
variable2 : LongDataType;
variable3 : BOOL;
variable4 : BOOL;

//Alignment causes overflow
Line length limit                    |
LongVariableName1 : BOOL;
variable2         : LongDataType;
variable3         : BOOL;
variable4         : BOOL;
```
So there are case where i have no choice but to break the alignment in columns. This is even worse with comments.
Hope that this gives you some insights on the dilemma here

**Comment by crthomas1234** [comment]
Hi Gerhard.

Thanks for  your feedback on the topic. I agree on not having a single line
comments in the declaration if nothing more than the fact that it throws
off how Codesys adds the comment to the variable as it first takes the
comment above it before the one after it.  The code I was using was from a
project of the forge site, but it contained a lot of declarations so it
made a good example of what I was looking for.  So as I understand it, you
are rejecting my request as an improvement?  I am ok either way as this was
just a request to support how I like to do things,  But it wasn't clear if
that was a yes or no answer.

I also found that you run the plccoder.com website.  I have spent some time
on that site reading up on articles lately, so thank you for your work
there too.  You helped me understand some more deeper technical topics like
the abstract methods versus interfaces.

Kind regards,

Chris

**Comment by Barteling** [comment]
Yes on short term I don't see an perfect solution for this. But i'm constantly looking for improvement so definitely keep this in consideration. 

Glad you like PLCCoder! I hope to find some time to write some more content for that haha.
I close this issue but let me know if you have more ideas!

**Comment by crthomas1234** [comment]
Hey Gerhard,

I had a question for you, so I will just use this email thread.

I have a variable declaration section that when I select the format code,
then nothing happens.  This is the section:

[image: image.png]

Can you see any reason why the refactoring would be skipped here?  It works
in all of the other sections I have used so far.

BR,

Chris

**Comment by Barteling** [comment]
Hi Chris
Could you check the picture? i dont see any picture attached
