### ISSUE TITLE
STweep does not apply formatting when code contains statements that have no effect

### ISSUE THREAD

**Issue by tan-wei-xin-alez** [Barteling/STweep#55]
**Describe the bug**
Formatting the following code with STweep
```
FUNCTION TestFunction : BOOL
VAR_INPUT
	in1: BOOL;
	in2: BOOL;
	in3: BOOL;
END_VAR
```
```
PROGRAM TestPOU
VAR
	test: BOOL;
END_VAR
```
```
test;

test := TestFunction(in1:=test, in2:=test, in3:=test);
```
results in no change in CODESYS even though `InvocationParametersLineBreakMode` has been set to "Break always"

Even utilizing conditional formatting (doesn't matter whether via comments or pragmas) does not yield formatted code as seen below
```
{STweep.disable}
test;
{STweep.enable}

test := TestFunction(in1:=test, in2:=test, in3:=test);
```

Only by commenting out the statement which has no effect does the code change as seen below
```
// test;

test := TestFunction(in1:=test,
                     in2:=test,
                     in3:=test);
```

**Expected behavior**
Even if statements which have no effect are not supported, conditional formatting should still work as seen below
```
{STweep.disable}
test;
{STweep.enable}

test := TestFunction(in1:=test,
                     in2:=test,
                     in3:=test);
```
Otherwise, an error should be thrown to warn the user that formatting was not possible as well as the cause of the error

**STweep version info**
STweep formatter for Codesys 4.0.0

**IDE version info**
CODESYS V3.5 SP16 Patch 4 + (32-bit)

**STweep settings**
[codesys_formatting.txt](https://github.com/Barteling/STweep/files/8125721/codesys_formatting.txt)

**Comment by Barteling** [comment]
Hi @tan-wei-xin-alez 
I can repeat this,

The problem is that STweep sees `test;` as an unknow statement/parsing error. And if there are parsing errors formatting is not executed because STweep cannot be sure what to do/expect.

But I noticed that Codesys is fine with `Test;` and only gives a compiler warning.
I'll add this on the todo list. 
Thanks for noting.
