### ISSUE TITLE
Erroneous code is deleted

### ISSUE THREAD

**Issue by nbuchele-KAMP** [Barteling/STweep#57]
**Describe the bug**
When I formatted my code, it deleted text. I was under the impression that it would **never** delete any code, aside from whitespace. Is this an accurate assumption? Specifically, I had the line seen below:
`bGRN	%I*	: BOOL;`
After formatting, it looks like this:
`bGRN		: BOOL;`

**Expected behavior**
I realize that I forgot to add the 'AT' before the '%I*' in this code. However, I would expect STweep to simply not format this code since it isn't correct.

**STweep version info**
STweep for TwinCAT 4.0.1

**IDE version info**
TcXaeShell Version 15.0.28307.1300. D15.9

**Additional context**
Please let me know if my assumption about the formatter never removing text being true. If it isn't, I will make a feature request that this get's added as a feature.
[STweep_settings (2).zip](https://github.com/Barteling/STweep/files/8225223/STweep_settings.2.zip)

**Comment by Barteling** [comment]
Your assumption are correct, Stweep should never delete code, and only modify whitespace.
Stweep should not format your code when there are parsing errors, but apparently something goes wrong here.
I'll check it.

**Comment by Barteling** [comment]
I improved this the latest release, both Codeys and TwinCAT
