### ISSUE TITLE
STweep not found on google

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#58]
I just wanted to download STweep and googled "download STweep", but no results showed up. There was only one relevant result from the CODESYS store. Otherwise it mostly showed results for "download Sweep". Is https://www.stweep.com/ not indexed by google?

**Comment by I-Campbell** [comment]
When I search it, it thinks stweep is a typo of steep.

This guy seems to offer a solution of "just ignore it until it goes away."
https://support.google.com/webmasters/thread/24875935/google-thinks-my-name-is-a-mispelling?hl=en

**Comment by Barteling** [comment]
I guess the release page is not that popular then, it should be included by google indexing..
Just keep searching^^

Or go to www.stweep.com/releases
