### ISSUE TITLE
Changes to spaces arund assignment operator in function block not saved

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#59]
I tried to disable the "Spaces > Binary operators > Around assignment operator in function block initializer parameter assignment", but this option not saved somehow. If I uncheck another option, for example "Spaces > Binary operators > Around equality operator", it gets saved. 

As a workaround I tried to save the settings, change it manually and import them, but then I get a checksum error :p.

- STweep for TwinCAT 4.0.2
- Microsoft Visual Studio Community 2019 Version 16.11.13

**Comment by Barteling** [comment]
Hmm I cannot repeat it,
Does the preview screen work ?
Does the form mention a change left of the control buttons
![1](https://user-images.githubusercontent.com/33071638/164676371-f2555455-bc53-4fa1-b062-15c854b4647c.PNG)
?

**Comment by rruiter87** [comment]
> Does the preview screen work ?

Yes

> Does the form mention a change left of the control buttons

Yes

See it in action

![stweep_settings](https://user-images.githubusercontent.com/98890535/164677990-2cf03ed9-03d4-4f81-839e-b605d67dab8d.gif)

**Comment by Barteling** [comment]
My bad i didnt read your first post well, i tested the 'Around assignment operator' instead of the 'Around assignment operator in function block initializer parameter assignment '

I can confirm the bug, i'll check what's going on.

**Comment by Barteling** [comment]
This is fixed in the latest releases of both Twincat and Codesys
