### ISSUE TITLE
Alignment of comparison

### ISSUE THREAD

**Issue by crthomas1234** [Barteling/STweep#60]
The formatter will align assignment operators but it will not align comparison operators.  Is this an option or can it be improved?

![CodeAfterFormatUsed](https://user-images.githubusercontent.com/98989074/168639862-bae65daf-0a37-4063-8f4d-adeae2f59a1e.png)

**Comment by Barteling** [comment]
Hmm, I understand what you want, 
No at this moment it is not possible.

You are right about the assignment operator, but it doesnt work with any comparison operator like '=' or '>' or '<='
Maybe a general option where you could align operators withing the same expression could do something like this:

```
var1 := A > B OR
   C   <> D OR
   EEE <= F OR
   G   <  H; 
```

Not sure how much I like that, but that a matter of taste of course.

**Comment by crthomas1234** [comment]
Hi Gerhard,

I like your proposal for a general option for the feature.  Your alignment
proposal is also what I was thinking of as a solution.

Thank you for the response.

Regards,

Chris

**Comment by Barteling** [comment]
I'll add it to my list, 
I dont think it will be released on short term, but i'll see what i can do.

**Comment by crthomas1234** [comment]
Thanks!
