### ISSUE TITLE
Idea: Marketplace release

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#62]
Maybe an idea to add an nuget release? Then it would be much easier to update to the latest version.

**Comment by Barteling** [comment]
Nuget is more intended to add dll's etc to your current project is'nt it?

I think the marketplace is more something i should look at:
https://marketplace.visualstudio.com/

**Comment by rruiter87** [comment]
Ah yes that is correct.

**Comment by Barteling** [comment]
It is on my bucket list
