### ISSUE TITLE
Formatting support for local/implicit enums

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#63]
The following code is reformatted, despite being much shorter than 100 characters. I guess it is because these types are not recognized?

```
// Before
VAR
    step : (FirstFlash, SecondFlash, Assert, Finished) := FirstFlash;
END_VAR

// After
VAR
    step : (
        FirstFlash,
        SecondFlash,
        Assert,
        Finished
    ) := FirstFlash;
END_VAR
```

- STweep 4.0.4
- [settings.txt](https://github.com/Barteling/STweep/files/8762568/settings.txt)

**Comment by Barteling** [comment]
Apologies for the late reaction, i missed this issue.

But thanks for noting, i agree this is not correctly formatted.
STweeps support for implicit enums is limited. (STweep uses the formatting style from a explicit type declaration where you typically have a member on each line.)

I'll see if I can enhance this in a future release

**Comment by Barteling** [comment]
Added in 4.1.0- Beta
https://www.stweep.com/beta-releases/
