### ISSUE TITLE
No linebreak when a comment pushes a line above 100 chars

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#64]
```
// Before
TYPE Status :
STRUCT
    EncoderWarning : BIT; // Bit 0 of received data, should be ENCODER WARNING in all BiSS C encoders.
    EncoderError : BIT; // Bit 1 of received data, should be ENCODER ERROR in all BiSS C encoders.
END_STRUCT
END_TYPE

// After
TYPE Status :
STRUCT
    EncoderWarning :
        BIT; // Bit 0 of received data, should be ENCODER WARNING in all BiSS C encoders.
    EncoderError : BIT; // Bit 1 of received data, should be ENCODER ERROR in all BiSS C encoders.
END_STRUCT
END_TYPE
```

The desired effect would be no change. With the line break, the comment doesn't show in the online view. 

![image](https://user-images.githubusercontent.com/98890535/179002476-e40bc019-8bc1-46ac-aabb-950edc6fcce0.png)

I looked through the settings and I couldn't find one which fixes this. Or did i miss it? Note that as soon as the reformatted line would go above 100, STweep doesn't reformat anymore.

```
// This one doesn't reformat
TYPE Status :
STRUCT
    EncoderWarning : BIT; // Bit 0 of received data, should be ENCODER WARNING in all BiSS C encoders. dfdsf dsfr
    EncoderError : BIT; // Bit 1 of received data, should be ENCODER ERROR in all BiSS C encoders.
END_STRUCT
END_TYPE
```

[settings.txt](https://github.com/STweep/STweep/files/9112515/settings.txt)

**Comment by Barteling** [comment]
Hmm tricky.
Basically STweep is doing the right thing in my opinion.

You have a line limit of 100, the EncoderWarning declaration exceeds this.
if stweep breaks the declaration the line length limit is respected.

If you make the comment a bit longer, as you showed line breaking does change the fact the line length is exceeded, so Stweep leaves it as is.

So it does as it is asked. However I did not know/take in account that by breaking this way the comment does not show up in the online debugger anymore.. 

Perhaps this would be a better solution, but i don't know if this has any other consequences?
```
TYPE Status :
STRUCT
    // Bit 0 of received data, should be ENCODER WARNING in all BiSS C encoders.
    EncoderWarning : BIT; 
    EncoderError : BIT; // Bit 1 of received data, should be ENCODER ERROR in all BiSS C encoders.
END_STRUCT
END_TYPE
```

**Comment by HAHermsen** [comment]
You should try (* *) as multi line comment

**Comment by rruiter87** [comment]
Thanks for the suggestions @Barteling  and @HAHermsen. I now fixed it by either removing character so the whole line is <100 char _or_ adding some to make the comment line + indent exceeds 100 chars. 

I agree STweep is doing the right thing. It was just a bit annoying.
