### ISSUE TITLE
Option for newline at start of file

### ISSUE THREAD

**Issue by WS-nfi** [Barteling/STweep#68]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Twincat places `<ST><![CDATA[` in front of its first line (A). If new code (B) is written before the previous first line (A), git wrongly thinks that line (A) has changed.  This also happens at the end of the file, however a a check can be set to add a newline at the end of the file.
![image](https://user-images.githubusercontent.com/111277213/184611157-6ae8b2c8-f1ad-4a13-999e-4776574ef78b.png)

**Describe the solution you'd like**
Please, also add a check for a newline at the start of the file

**Comment by WS-nfi** [comment]
Not a check but an Int.
![image](https://user-images.githubusercontent.com/111277213/184612310-92c2a8e3-e5ce-4dbc-bce3-798983076970.png)

**Comment by Barteling** [comment]
Should be doable, 
I'll see if I can implement this is a future release

**Comment by slimeth** [comment]
What's the status on this feature?

**Comment by Barteling** [comment]
It's on the list, but not with the highest priority

**Comment by masterprinter** [comment]
Is there any progress on this feature?
Like @WS-nfi I too have this issue that our versioning system thinks that the first line has changed if I dont add an empty line.
I now have to manually add the newline at the start of every file.
This feature could save me countless hours of manual formatting.
Please consider increasing priority of this feature.

**Comment by Barteling** [comment]
Added in the latest beta:
https://www.stweep.com/beta-releases/
