### ISSUE TITLE
No newline at end of file if last line is a comment

### ISSUE THREAD

**Issue by WS-nfi** [Barteling/STweep#70]
**Describe the bug**
When a newline is set to be at the end of the file, no newline is at end of file if last line is a comment

**Expected behavior**
Expect a new line

**STweep version info**
"STweep for TwinCAT 4.0.4"

**IDE version info**
Twincat v15

**Additional context**
![image](https://user-images.githubusercontent.com/111277213/188895557-cfd851d8-1498-4df9-85da-1f070faf71aa.png)

**Comment by Barteling** [comment]
I cannot repeat this,
Perhaps it's related to your specific settings set could you send me an export of your settings? (Change the extension to .txt to upload it here).

**Comment by WS-nfi** [comment]
This is one of the methods:
![image](https://user-images.githubusercontent.com/111277213/190582858-02a39ac8-79c6-4c88-b7c4-1b2a4cd8fb6a.png)

**Comment by WS-nfi** [comment]
[STweep_Options.txt](https://github.com/STweep/STweep/files/9581727/STweep_Options.txt)

**Comment by Barteling** [comment]
Yep got it, will work on a solution

**Comment by Barteling** [comment]
This should be solved in 
4.1.3-Beta
https://www.stweep.com/beta-releases/
