### ISSUE TITLE
No indent in Case if it is only a variable

### ISSUE THREAD

**Issue by WS-nfi** [Barteling/STweep#71]
**Describe the bug**
In a Case statement a line with a variable and a ";" is gets no indent by STweep

**Expected behavior**
Proper indentation is expected

**Additional context**

**Comment by WS-nfi** [comment]
![image](https://user-images.githubusercontent.com/111277213/190581391-c2901da5-60ad-4069-b7fa-9331b7aaef7c.png)

**Comment by Barteling** [comment]
hmm, i can confirm this, 

i don't think it only in the case statement, more a general thing, 
STweep does not understand why you would have a single variable there, so it leaves it as it (if you indent it manually it stays there).

So, why do you have a single variable placed in your case?

**Comment by WS-nfi** [comment]
Twincat also gave me a warning about it.
I indented it manually and then asked STweep to restructure, but it removed the indent.
![image](https://user-images.githubusercontent.com/111277213/190592262-20f0cbb6-d5ce-4bfd-86f1-40d43408c654.png)

Its a nice debug feature to have the latest errorReason in the Error state. This means I don't have to go looking for it.

**Comment by WS-nfi** [comment]
Since it works I have not made the time to look for a warning-less way to do it.

**Comment by Barteling** [comment]
I improved this in the latest beta, let me know your findings!
https://www.stweep.com/beta-releases/

**Comment by WS-nfi** [comment]
Thank you!
