### ISSUE TITLE
Comment alignement not perfect

### ISSUE THREAD

**Issue by GISED-Link** [Barteling/STweep#73]
**Describe the bug**
```pascal
 // some comment
CASE state OF
// some comment
0:
    //some comment
    IF toto = 2 THEN
        //some comment
        state := 1;
        //some comment <<<<< missaligned (in my opinion)
    ELSIF toto = 3 THEN
        // some comment
        state := 1;
        // some commet <<<<< missaligned (in my opinion)
    ELSE
        // some comment
        state := 1;
        // some comment <<<<< missaligned (in my opinion)
    END_IF

    // some comment
    IF toto = 4 THEN
        // some comment
        state := 1; // some inlinged comment
        // next part of the alligned comment <<<<< missaligned (in my opinion)
    END_IF

//some comment
1:
    // some comment
    state := 2;
    // some comment <<<<< missaligned (in my opinion)
ELSE
    // some comment
    state := 0;
    // some comment <<<<< missaligned (in my opinion)
END_CASE
```

**Expected behavior**
If possible, I would have my comment at the same alignement as the ELSIF and ELSE element.
Exception:
```pascal
    // some comment
    IF toto = 4 THEN
        // some comment
        state := 1; // some inline comment
        // next part of the inline comment <<<<< missaligned (in my opinion)
    END_IF
```
Here I would like to have the comment before the END_IF aligned with the previous one

**STweep version info**
Twincat XAE 4.1.2
('bug' was always there, I just write the issue now)

**Additional context**
This is not something that causes me any problem. I have no idea how other formatters handle this kind of thing

**Comment by Barteling** [comment]
I think I agree, I'll see what I can improve

**Comment by klementuel** [comment]
I have the same problem and wanted to ask when the error will be fixed.

**Comment by Barteling** [comment]
I looked into it, but there can be strong user preference here so i'm trying to come up with some settings to solve this for evertone

**Comment by Barteling** [comment]
I improved on this in the latest Beta version, with some optional settings. 
Let me know your findings!
https://www.stweep.com/beta-releases/
