### ISSUE TITLE
Wrong line Brake 

### ISSUE THREAD

**Issue by Schorsch1991** [Barteling/STweep#74]
**Describe the bug**
The line Brake following line brake is not so nice. 

![grafik](https://user-images.githubusercontent.com/97521719/197952220-3c46c5e8-cb14-4124-a52a-bec03ca1039e.png)

**Expected behavior**
i think it is better to make a new line in Arguments of Methode like the following
![grafik](https://user-images.githubusercontent.com/97521719/197952963-4555824e-f535-44e6-b1b9-23c0b7a4fc6f.png)

**STweep version info**
STweep for TwinCAT 4.1.2

**IDE version info**
Twincat XAE Shell with Twincat 4024.29.0.0

**Comment by Barteling** [comment]
Could you send me your setting files as well?
It is possible with some slightly different settings

**Comment by Schorsch1991** [comment]
Yea shure.



Von: Gerhard Barteling ***@***.***>
Gesendet: Mittwoch, 26. Oktober 2022 09:41
An: STweep/STweep ***@***.***>
Cc: Georg Vogt ***@***.***>; Author ***@***.***>
Betreff: Re: [STweep/STweep] Wrong line Brake (Issue #74)


Could you send me your setting files as well?
It is possible with some slightly different settings

-

**Comment by Schorsch1991** [comment]
[StweepSettings.zip](https://github.com/STweep/STweep/files/9867260/StweepSettings.zip)

**Comment by Barteling** [comment]
You should have a look at the following settings:
Wrap long lines at : 200
Maximum invocation parameters on single line 4:
Invocation parameters line break mode : Break if line length overflow or multiline.

STweep always tries to place as much code on a single line, unless told other wise by the settings.
So in this case by doing the above it could do the job with one line break.

if you do not want this consider:
 1 settings the maximum invocations parameters on a single line to 3 instead to 4
 2 Reduce the line length limit to 150 for example
 3 Invocation parameters line break mode to Always, will force stweep to always wrap argument parameters.

changing 1 or 2 is probably what you are looking for.

Have a look at Keep existing line breaks, is true, Stweep will not restore the already formatted line break.


![afbeelding](https://user-images.githubusercontent.com/33071638/198012374-959b7422-9905-4c27-9487-dc96507b4ea2.png)

**Comment by Schorsch1991** [comment]
Thank your Gerhard for Explanation.

Greatings from Germany



Von: Gerhard Barteling ***@***.***>
Gesendet: Mittwoch, 26. Oktober 2022 13:16
An: STweep/STweep ***@***.***>
Cc: Georg Vogt ***@***.***>; Author ***@***.***>
Betreff: Re: [STweep/STweep] Wrong line Brake (Issue #74)


You should have a look at the following settings:
Wrap long lines at : 200
Maximum invocation parameters on single line 4:
Invocation parameters line break mode : Break if line length overflow or multiline.

STweep always tries to place as much code on a single line, unless told other wise by the settings.
So in this case by doing the above it could do the job with one line break.

if you do not want this consider:
1 settings the maximum invocations parameters on a single line to 3 instead to 4
2 Reduce the line length limit to 150 for example
3 Invocation parameters line break mode to Always, will force stweep to always wrap argument parameters.

changing 1 or 2 is probably what you are looking for.

Have a look at Keep existing line breaks, is true, Stweep will not restore the already formatted line break.

[afbeelding]<https://user-images.githubusercontent.com/33071638/198012374-959b7422-9905-4c27-9487-dc96507b4ea2.png>

-
