### ISSUE TITLE
1User and multiple computer license

### ISSUE THREAD

**Issue by vmax77** [Barteling/STweep#75]
Problem: 
Having to purchase license per device instead of per person seems a bit cumbersome. Since in our team, we usually have a "commissioning" computer we tend to take on-site and usually air-gapped and our main computers at our desks which is inside the company network. I am sure we are not unique in this issue

Solution: 
Having Tiered licensing such as :
- 1xUser 1xDevice
- 1xuser 3xDevice
- 1xCompany - Per device licenses

Thank you for the amazing work :)

**Comment by Barteling** [comment]
Hi Vmax77

If you order for example 5 license in one order in the webshop, you will receive 1 license key which can be activated up to 5 times parallel, The activation can be changed between workstations (manually), as long as the total activation count is lower than 5. i guess this basically cover your tier 1 and 2

I have local floating licenses available, but this starts to be interessting for companies with more than 30 users.

I'm working on floating cloud license. if you close you instance of visual studio or xae shell your license is checked in, if you start another xae shell on another computer it will automatically check out you license again.  Same principle as now basically, but automated.


Hope this gives you more info on the available systems, and of course thanks for your input!
