### ISSUE TITLE
Remove trailing whitespace of comment

### ISSUE THREAD

**Issue by GISED-Link** [Barteling/STweep#76]
```pascal
toto := toto + 1;
// comment with white space here ->                   		 		
foo(toto);
```

I don't need those extra bytes in my files :)

Maybe add a checkbox with "remove trailing whitespace from comment" or something like that? I don't know if it is a good thing for everyone... Especially for those with ugly file headers 🤷🏻‍♂️

**Comment by Barteling** [comment]
Thanks for you input!
I'll add this to me idea list, but don't expect it on short term

**Comment by GISED-Link** [comment]
I have no idea how you tokenize the comments... But if you have the complete line inside a token you could easily trim the end:
https://www.tutlane.com/tutorial/csharp/csharp-string-trim-method-trimstart-trimend#:~:text=In%20c%23%2C%20the%20string%20TrimEnd,array%20from%20the%20string%20object.

**Comment by Roald87** [comment]
You can also remove trailing spaces with a pre-commit hook as I explain [here](https://cookncode.com/twincat/2022/04/14/pre-commit.html#twincat-relevant-pre-commits)
