### ISSUE TITLE
Add support for STRUCT PERSISTENT

### ISSUE THREAD

**Issue by masterprinter** [Barteling/STweep#78]
**Describe the bug**
Formatting  STRUCT PERSISTENT triggers a parsing error.
![Struct Persistent](https://user-images.githubusercontent.com/23361615/227954905-8c8cfb37-d3b9-4c96-a5f9-31789a0a79cc.PNG)

**Expected behavior**
Accept STRUCT PERSISTENT and format like an usal STRUCT.

**STweep version info**
"STweep for TwinCAT  4.1.2"

**IDE version info**
"Microsoft Visual Studio Professional 2019 Version 16.11.16"

**Additional context**
[Settings.txt](https://github.com/STweep/STweep/files/11079218/Settings.txt)

**Comment by HAHermsen** [comment]
Hi,

To me this doesn't seem a bug but a non conformal usage of the keyword PERSISTANT. 

In general it is unwise to decorate DUT's with a additional keywords. Keywords like STAT or CONSTANT or PERSISTANT etc. should be added at the declaration part in the header of the program, or FB or F. If you keep the DUT declaration clean, your application specific instance can be more flexible.

Regard the following and omit persistent from your dut declaration(!);

VAR PERSISTANT
    MyPersistatntUT :  stTestStruct;
END_VAR
VAR_STAT
   MyStaticDUT : stTestStruct;
END_VAR

**Comment by masterprinter** [comment]
Hi,

I do fully agree that its bad practice to use these Keywords inside of DUT's.
And I know it would be better to put it in the DUT declaration.

The DUT I posted in my issue report was only an example.
The PERSISTENT DUT_1  I'm dealing with is part of another NON-PERSISTENT DUT_2
I dont want all variables of DUT_2 to be PERSISTENT.
I only want the variable of Type DUT_1 to be PERSISTENT.

>TYPE DUT_2:
   STRUCT
      per : DUT_1; // Persistent
    boo : BOOLEAN; // non Persistent
END_STRUCT
END_TYPE

That's the reason why some of the projects at our company use DUT's which are decorated with the Keyword PERSISTENT.
These projects were written by a external company btw.
In new projects we do use different DUT's for Persistent and non-Persistent variables.
But in all of our old projects it would be very timeconsuming to change something in the DUT_2 structure since its used in countless places in the PLC and HMI code.

And since it's possible to use it in TwinCat without a problem it should also be possible to format the code without an error.

If there's an easy way to fix my issue I'm all ears.

**Comment by Barteling** [comment]
I did add support for this in a new beta whcih is to be expected soon

**Comment by masterprinter** [comment]
Great to hear!
I'm looking forward to the next release.
I appreciate the work you put in this extension🙏

**Comment by Barteling** [comment]
Hmm just released 4.1.3-Beta, but realized that i only added support for RETAIN, not persistent,  i'll add the PERSISTENT keyword in the next release

https://www.stweep.com/beta-releases/

**Comment by masterprinter** [comment]
If you're at it, it would be nice if  you could add support for CONSTANT as well.
Just to cover all three attribute keywords from beckhoff : [https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2528848523.html&id=](url)

**Comment by Barteling** [comment]
Added!
https://www.stweep.com/beta-releases/
