### ISSUE TITLE
Add parsing/reformat for single line and multiline comment blocks optionally

### ISSUE THREAD

**Issue by HAHermsen** [Barteling/STweep#8]
It would be usefull to have STweep also parse/reformat comments optionally:

Personally I prefer to see all single line comments with a trailing space:

`
//Not this!

// But this :-)

`
Also some rules could be applied to multiline comments (aka comment blocks):

`(*A multiline block on a single line*) `
transform into something like:
`
(* 
    A multiline block spreaded like a codeblock would be spreaded,

    over multiple lines and with leading spaces (or tabs according the the spaces tabs settings)
*)
`

A rule could be applied to always auto-enforce a single 'multi line codeblock' e.g:
`(*This is an example *)`
transforms into 
`(* 

    This is an 

    example

*)`
or even a multi 'single line comments' spreaded over multiple lines (or even vice versa);
`

// This is an

// example

`

**Comment by HAHermsen** [comment]
wow MD isn't helping me ;-) plus I am way too lazy!

**Comment by Barteling** [comment]
This might be usefull, but also tricky to implement, Structured text at least has some rules to follow, comments are completely random. Of course a space after // is doable.

But it would rather put some energy in parsing pragma's first. 
I'll put this on my feature list, but not with an very high priority ^^

**Comment by Roald87** [comment]
> wow MD isn't helping me ;-) plus I am way too lazy!

@HAHermsen you know there is a preview?

**Comment by Roald87** [comment]
I think formatting of multi-line comments shouldn't be too difficult if they are the only thing on that line. You could just look for the first word which exceeds the maximum line length and break before this word. Or am I missing something?

This option would be convenient if you want to format the docstring of a function block or method.

**Comment by Barteling** [comment]
I've some commented out code in my POU:
<pre>
(* IF TRUE THEN
    Invoke();
END_IF 
FOR I:=0 TO 5 DO
    Invoke(i);
END_FOR*)
</pre>

What should the formatter make of this?

**Comment by Roald87** [comment]
Well you shouldn't have done that :p.

More seriously it is a fair point. Maybe only format lines which are too long?

Anyway I see the complexity now, better focus on the other features first.
