### ISSUE TITLE
STweep add an unnecessary tab before a comment placed after the pragrma {STWeep.Enable}

### ISSUE THREAD

**Issue by GISED-Link** [Barteling/STweep#80]
**Describe the bug**
In the code below:
```Pascal
{STWeep.disable}
// some awsome code
{STWeep.Enable}

    // The best comment ever

IF something THEN
    // do something
END_IF
```

`// The best comment ever` is not placed correctly. The tab before is forced by STweep. I have not tested for everything, but seems to be only a problem for comment and other attribute pragmas. Other pragrma will behaves like this (it can be anything inside the {}) :
```
{STWeep.disable}
{STWeep.Enable}

    {STWeep.disable}   <---- should not have a tab
    {STWeep.Enable}    <---- should not have a tab
```

**Expected behavior**
```Pascal
{STWeep.disable}
// some awsome code
{STWeep.Enable}

// The best comment ever    <----- better

IF something THEN
    // do something
END_IF
```

**STweep version info**
STweep for TwinCAT 4.1.2

**Comment by Barteling** [comment]
Thanks for reporting, i'll check

**Comment by Barteling** [comment]
I cannot reproduce this, can you share your settings?

**Comment by GISED-Link** [comment]
Ok now I have taken the time to finally test it again. With version 4.2.3 and try it again here and there in my code, seems not to occure again. I think you can close it.

**Comment by klementuel** [comment]
Hello,
I have a similar problem,
that my comments are being posted incorrectly.

In this case I have a if else clause with nested If else clauses and would like the comments to be aligned with the IF Else indentations

It look like this:

````st

  // Comment
  IF xxx THEN
  
      // Comment
      IF xxx THEN
          IF xxxx THEN
              Logic
          ELSIF xxx THEN
             Logic
          ELSIF xxx THEN
              Logic
          ELSE
              Logic
          END_IF
  
          // Comment Wrong indent
      ELSIF xxx THEN
         Logic
  
          // Comment Wrong indent
      ELSIF xxx THEN
          Logic
      ELSIF xxx THEN
         Logic
  
          // Comment Wrong indent
      ELSE
          // Comment
          Logic
  
      END_IF

```

**Comment by klementuel** [comment]
Sorry just saw that there is already the same bug unfortunately not yet fixed 
https://github.com/STweep/STweep/issues/73

**Comment by Barteling** [comment]
duplicate #73
