### ISSUE TITLE
Automatic uppercase for Keywords

### ISSUE THREAD

**Issue by MotronicAG** [Barteling/STweep#81]
I have just installed the trial of STweep in TwinCAT XAE Shell. It works as expected so far, but I am missing one thing:

A function for automatic conversion of keywords to UPPERCASE is missing.

Why do i not use the Build-in Feature in the TwinCAT options: TwinCAT->PLC Environment->Smart coding->Convert keywords to uppercase automatically?
Because this feature must be deactivated when you make use of th "TcLinkTo" Attribut. It formats the pragma code broken and drives you crazy. So, its always deactivated, but i want the keywords (like BOOL, IF, CASE, WORD, etc.) to be UPPERCASE.

When you implement this, i will buy an license of it.

Thank you!
Ralf

**Comment by Barteling** [comment]
Thanks for the suggestion Ralf! i had the request before so i take it along but the priority is not very high at the moment for this feature, i'll keep you posted!

**Comment by MotronicAG** [comment]
OK Thanks!
Especially for integration into a Build server it would be very cool!

**Comment by Barteling** [comment]
Added in 4.4.1 - Beta
https://www.stweep.com/beta-releases/
