### ISSUE TITLE
Region identification 

### ISSUE THREAD

**Issue by SimmelFlo** [Barteling/STweep#82]
Currently do not see any possibility to create a Tab-In inside of Regions:
![image](https://github.com/STweep/STweep/assets/108086424/566eefb3-70c5-4f9b-88de-0af02431d97e)

Desired configuration:
![image](https://github.com/STweep/STweep/assets/108086424/5c4656b9-e384-4adf-8074-6c0840f56402)

**Comment by Barteling** [comment]
Thanks, this is something which is on my  list,!
