### ISSUE TITLE
Issues with Array of Structs

### ISSUE THREAD

**Issue by ksanita** [Barteling/STweep#87]
**Describe the bug**
There are two issues here:
1. Struct initializations within an array of structs don't receive assignment alignment
2. Comments after the last struct member cause the parentheses to get tabbed over by 1

**Expected behavior**
Image below shows both the STSweep formatting as well as what I would expect the formatting to look like

![image](https://github.com/STweep/STweep/assets/88203276/ccc34ee8-52c9-4376-acee-d2e6c54d03df)

**STweep version info**
STweep for TwinCAT 4.2.3

**IDE version info**
TcXaeShell Version 15.0.33403.129 D15.9

**Additional context**
No additional context as of now.

**Comment by Barteling** [comment]
Kevin, could you share an export of your settings as well as the source code in text? (Saves me the typing :-) )

**Comment by ksanita** [comment]
Will do! Attached is the example and the export. I had to rename the export as .txt because Github didn't like the .stsweep extension. If that causes issues just let me know how to get it to you without Github complaining.

[STSweepExample.txt](https://github.com/STweep/STweep/files/14844073/STSweepExample.txt)
[STSweepExport.txt](https://github.com/STweep/STweep/files/14844074/STSweepExport.txt)

**Comment by Barteling** [comment]
Thanks Kevin, I could identify and solve the bug quickly, it will be fixed in the next release, due to some other more significant improvements this likely be first available through the Beta channels, i'll post a link here when ready.

**Comment by ksanita** [comment]
@Barteling Great, thank you!

**Comment by Barteling** [comment]
I fixed this in the latest beta, let me know your findings!
https://www.stweep.com/beta-releases/
