### ISSUE TITLE
Support for TwinCAT XAE 4026.x

### ISSUE THREAD

**Issue by MotronicAG** [Barteling/STweep#89]
Hi

Now that the 4026 has finally been officially released (although it is still not recommended for productive use for some time), STweep should be made fit for it.

Currently the installer for XAE Shell cannot be installed, although the XAE Shell 4026 workload is installed. Message:
This application requires TwinCAT XAE Shell. Please install TwinCAT XAE Shell then run this installer again.

Thanks Ralf

**Comment by Barteling** [comment]
Yep im actively working on it, ran in some technical challanges but it will be released soon

**Comment by MotronicAG** [comment]
Great to hear!
