### ISSUE TITLE
Improve array struct

### ISSUE THREAD

**Issue by Barteling** [Barteling/STweep#9]
Not sure if this is a feature or a bug. 

Anyway. When formatting the lines below, I do not want to change them. Currently they do change, I guess because I set the keep existing line breaks to false. However, this is not the way to format a struct I would argue.

```
// in
FUNCTION POU : BOOL
VAR_INPUT
	SomeArrayWithStruct : ARRAY[1..2] OF ST_Struct := [
		(var1 := 728, var2 := 503, var3 := 209, var4 := 1539, var5 := 1), 
		(var1 := 728, var2 := 503, var3 := 209, var4 := 1539, var5 := 1)
	];
END_VAR

// out
FUNCTION POU : BOOL
VAR_INPUT
	SomeArrayWithStruct : ARRAY[1..2] OF ST_Struct := [(var1 := 728, var2 := 503, var3 := 209, var4
		:= 1539, var5 := 1), (var1 := 728, var2 := 503, var3 := 209, var4 := 1539, var5 := 1)];
END_VAR
```

- STweep version 1.0.5-beta
- [settings.txt](https://github.com/Barteling/STweep/files/5802213/settings.txt) (had to change extension to txt, because GitHub doesn't accept .STweep files :p.

**Comment by Barteling** [comment]
submitted by @Roald87 (sorry deleted your original issue)

**Comment by Barteling** [comment]
I fixed this in 1.0.6-Beta for TwinCAT, just released. And for Codesys 1.4.4-Beta (not yet released).

Formatting result with line break at 100 and keep existing line breaks turned of.

`FUNCTION POU : BOOL
VAR_INPUT
    SomeArrayWithStruct : ARRAY[1..2] OF ST_Struct := [
        (var1 := 728, var2 := 503, var3 := 209, var4 := 1539, var5 := 1),
        (var1 := 728, var2 := 503, var3 := 209, var4 := 1539, var5 := 1)];
END_VAR`

**Comment by Roald87** [comment]
Just tested with v1.0.6-beta and for the example it is working. However, that was an anonymized sample. I just tested it with the real code and there it failed. I tried to locate the point of failure and there seems to be an issue with the last struct element:

```
// in
FUNCTION POU : BOOL
VAR_INPUT
	SomeArrayWithStruct  : ARRAY[1..2] OF ST_Struct  := [
		(var1:=728, var2:=503, var3:=209, var4:=1539, var5:=1),
		(var1:=720, var2:=498, var3:=215, var4:=1460, fM:=1)
	];
END_VAR

// out
FUNCTION POU : BOOL
VAR_INPUT
	SomeArrayWithStruct : ARRAY[1..2] OF ST_Struct := [(var1 := 728, var2 := 503, var3 := 209,
		var4 := 1539, var5 := 1), (var1 := 720, var2 := 498, var3 := 215, var4 := 1460, fM := 1)];
END_VAR
```

but if I change `fM` to `var5` is works.

**Comment by Barteling** [comment]
The change fm to var5 trigger an length overflow on that line. With fm the line length is <100 so the formatter is happy with the result.

In general the formatter consider line breaks as bad. if it can do it with one line break it wont do it in two.  With Var5 it does need two breaks so in that case  it's fine for the formatter to keep a struct initializer on one line.


This unless there are specific rules for a piece of code like there are for chained method call and function call arguments etc. 
Maybe i need that here as well.

**Comment by Barteling** [comment]
While working on the function block initializers from #21 I also anticipated on improvement on array structure initialization as described above. It won't be visible in the next beta but one of the releases shortly after.

**Comment by Barteling** [comment]
Improved with 3.1.0 Beta

**Comment by Roald87** [comment]
I just tried this again, but I still do not get the desired result. I've played around with the different options, but was unable to get the desired result.

```
// current in
VAR
	SomeArrayWithStruct : ARRAY[1..3] OF ST_Struct := [(var1:=728, var2:=503, var3:=209, var4:=1539, var5:=1),
		(var1:=720, var2:=498, var3:=215, var4:=1460, fM:=1)];
END_VAR

// current out 
VAR
	SomeArrayWithStruct :
		ARRAY[1..3] OF ST_Struct := [(var1:=728, var2:=503, var3:=209, var4:=1539, var5:=1),
		(var1:=720, var2:=498, var3:=215, var4:=1460, fM:=1)];
END_VAR

// desired
VAR
	SomeArrayWithStruct : ARRAY[1..3] OF ST_Struct := [
		(var1:=728, var2:=503, var3:=209, var4:=1539, var5:=1),
		(var1:=720, var2:=498, var3:=215, var4:=1460, fM:=1)
	];
END_VAR
```

- STweep v3.1.3
- [settings.txt](https://github.com/Barteling/STweep/files/6121750/settings.txt)

**Comment by Barteling** [comment]
I agree,
I'll check it.

**Comment by Barteling** [comment]
You need to set the parameter "Array initializer line break mode" to "Break if long or multiline". Now it was at "Break if long".
[settings.txt](https://github.com/Barteling/STweep/files/6125883/settings.txt)

You probably want this as well Structure Initializers line break mode.
I have to say that this option is not well visible in the UI i'll fix that.


Some background information:
A : ARRAY OF BOOL := [TRUE, FALSE, FALSE];
The array initializer can have the following splits,
Before left bracket, optionally
After left bracket, optionally,
After first comma,
After second comma,
Before right bracket.

If an initializer fits on one line the formatter is happy,  if for some reason there is a line break either existing or due to line length overflow, all of the splits will break **IF** you applied the mode "Break if line length overflow **or multiline**".  So all mentioned splits will be broken for the price of one line break.

If you have only "Break if line length overflow" the formatter would in this example need two line breaks to stay under the line length. This is more 'expensive' then placing one on earlier place in the line . hence the formatter chose for this way.

**Comment by Roald87** [comment]
I'm still a bit confused. However I now got it to work when I set __Array initializers > Array initializer parameters__ to __Break if line length overflow__ 

This is the result with these [settings_correct_linebreak.txt](https://github.com/Barteling/STweep/files/6128407/settings_correct_linebreak.txt)
```
METHOD Testing
VAR_INST
	SomeNumbers : ARRAY[1..n] OF LREAL := [
		0.8054, 0.8418, 0.8747, 0.9064, 0.9339, 0.9646, 0.9939, 1.0188, 1.0436, 1.0593,
		1.0752, 1.0897, 1.1005, 1.1102, 1.1118, 1.1106, 1.1129, 1.1071, 1.1072, 1.1007];
END_VAR


VAR CONSTANT
	n : UDINT;
END_VAR
```

If I set __Array initializers > Array initializer parameters__ to __Break if line length overflow or multiline__ this is the result

```
METHOD Testing
VAR_INST
	SomeNumbers : ARRAY[1..n] OF LREAL := [
		0.8054,
		0.8418,
		0.8747,
		0.9064,
		0.9339,
		0.9646,
		0.9939,
		1.0188,
		1.0436,
		1.0593,
		1.0752,
		1.0897,
		1.1005,
		1.1102,
		1.1118,
		1.1106,
		1.1129,
		1.1071,
		1.1072,
		1.1007
	];
END_VAR
VAR CONSTANT
	n : UDINT;
END_VAR
```

Or is that how it is supposed to work? 

Anyway if that is the case then the line breaks are ok. However, there is one thing which is not correct. With both examples I set ` "LineBreakBeforeRightBracketInArrayInitializer": true,`. In the first example it does not do the line break, but in the second example it does.

**Comment by Barteling** [comment]
yes that is how it supposed to work. Or at least how it does work right now
First example the array initializer is  broken due to line length, and perhaps maximum number of arguments. not all possible splits are broken because you set : Break if line length overflow, and there is no overflow any more. 
by setting "LineBreakBeforeRightBracketInArrayInitializer": true you basically say the this split belongs to array initializer so the same rules goes for this split as well. hence it;''s not broken.

Second example there is at least one line break so all splits in the initializer including the LineBreakBeforeRightBracketInArrayInitializer or broken

On second thought
perhaps the settings:
Line break before left bracket, 
line break after left bracket
line break before right bracket 
Should act just on the fact if the array intializer is multi line or not.

**Comment by Roald87** [comment]
> Should act just on the fact if the array intializer is multi line or not.

I think that would be much better, because that is easier to explain and it is what I (and most people?) would expect.

**Comment by Barteling** [comment]
@Roald87, STweep for TwinCAt 3.1.5-Beta changes this, can you have a look this beta?
