### ISSUE TITLE
Remote deactivation of licenses

### ISSUE THREAD

**Issue by rruiter87** [Barteling/STweep#90]
If I want to use the STweep CLI on a new computer, I have to deactivate the license on the old system first. Is it possible to remotely deactivate a license from the new system? This is convenient, especially if the old system doesn't exist anymore or is not available.

**Comment by Barteling** [comment]
He Roald,

What would prevent you from combining the activation and deactivation of STweep with your CLI script?
I suppose you constantly run the same script? 

Pseudo code
```
ActivateLicense -Key=xxxx
FormatCode
DeactivateLicense

```

**Comment by rruiter87** [comment]
What would prevent me? I didn't think of it :D. Thanks!

I use it in my pre-commit, but for that it would work as well.

**Comment by rruiter87** [comment]
I've added stweep with activation/deactivation to my TcTemplate pre-commit if anyone wants to use it as well.

https://github.com/rruiter87/tctemplate
