### ISSUE TITLE
Allow formatting of plain Structured Text files

### ISSUE THREAD

**Issue by ysmilda** [Barteling/STweep#96]
Our PLC Structured Text projects are contained within plain text files. These can't be formatted currently as it seems that STweep only supports the TwinCAT/Codesys XML formats. Would it be possible to support the plain text files as well?

**Comment by Barteling** [comment]
You could utilize the -Code input of STweep.CLI and input any plain ST you'd like and then write it back yourself

Powershell example, considering the file Code.txt:

```
$UnformattedCode = Get-Content .\Code.txt -Raw 
STweep.CLI format --settingsfile settings.stweep -c $UnformattedCode | Out-File -FilePath .\Code.txt
```

Could even be a one liner.

Let me know if this works for you
